//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWCFClient.EmployeeWCFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://ugo-omega.com/2020/11/02/Employee")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeWCFService.IEmployeeWCFService")]
    public interface IEmployeeWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeWCFService/GetEmployeeWCF", ReplyAction="http://tempuri.org/IEmployeeWCFService/GetEmployeeWCFResponse")]
        EmployeeWCFClient.EmployeeWCFService.Employee GetEmployeeWCF(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeWCFService/GetEmployeeWCF", ReplyAction="http://tempuri.org/IEmployeeWCFService/GetEmployeeWCFResponse")]
        System.Threading.Tasks.Task<EmployeeWCFClient.EmployeeWCFService.Employee> GetEmployeeWCFAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeWCFService/SaveEmployeeWCF", ReplyAction="http://tempuri.org/IEmployeeWCFService/SaveEmployeeWCFResponse")]
        void SaveEmployeeWCF(EmployeeWCFClient.EmployeeWCFService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeWCFService/SaveEmployeeWCF", ReplyAction="http://tempuri.org/IEmployeeWCFService/SaveEmployeeWCFResponse")]
        System.Threading.Tasks.Task SaveEmployeeWCFAsync(EmployeeWCFClient.EmployeeWCFService.Employee employee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeWCFServiceChannel : EmployeeWCFClient.EmployeeWCFService.IEmployeeWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeWCFServiceClient : System.ServiceModel.ClientBase<EmployeeWCFClient.EmployeeWCFService.IEmployeeWCFService>, EmployeeWCFClient.EmployeeWCFService.IEmployeeWCFService {
        
        public EmployeeWCFServiceClient() {
        }
        
        public EmployeeWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EmployeeWCFClient.EmployeeWCFService.Employee GetEmployeeWCF(int Id) {
            return base.Channel.GetEmployeeWCF(Id);
        }
        
        public System.Threading.Tasks.Task<EmployeeWCFClient.EmployeeWCFService.Employee> GetEmployeeWCFAsync(int Id) {
            return base.Channel.GetEmployeeWCFAsync(Id);
        }
        
        public void SaveEmployeeWCF(EmployeeWCFClient.EmployeeWCFService.Employee employee) {
            base.Channel.SaveEmployeeWCF(employee);
        }
        
        public System.Threading.Tasks.Task SaveEmployeeWCFAsync(EmployeeWCFClient.EmployeeWCFService.Employee employee) {
            return base.Channel.SaveEmployeeWCFAsync(employee);
        }
    }
}
